name: Check PR status

on:
  pull_request:
    branches: [ master ]
    types: [ edited, opened, reopened, synchronize, labeled, unlabeled ]

jobs:
  print_pr_details:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR number
      run: echo ${{ pull_request.number }}
      - name: Print PR status
      run: echo ${{ pull_request.status }}
