name: Check PR status

on:
  pull_request: [ master ]
  types: [ edited, opened, reopened, synchronize, labeled, unlabeled ]

jobs:
  Print PR details:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR number
      run: echo PR-${{ pull_request.number }}

      - name: Print PR status
      run: echo ${{ pull_request.status }}
